name: pytest

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types:
      - edited
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    name: Tests with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          pip install .
          pip install -r tests/requirements.txt

      - run: python -m pytest tests/
